/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistema.janelas;

import com.sistema.bd.ProfessorDAO;
import com.sistema.bean.Professor;
import com.sistema.listener.ProfessorAL2;
import excecoes.Excecoes;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import validacao.Valida;

/**
 *
 * @author Danrlei
 */
public class ConsultaProfessor extends javax.swing.JInternalFrame {

    private final ProfessorAL2 listener = new ProfessorAL2(this);
    private final ProfessorDAO dao = new ProfessorDAO();
    private Professor prof = new Professor();
    private Valida valida = new Valida();
    private String numbers = "0123456789";

    public ConsultaProfessor() {
        super("Consulta ao BD de Professores");
        initComponents();
        caregabanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prof = new javax.swing.JPanel();
        cnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cemail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        csexo = new javax.swing.JComboBox<String>();
        cendereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        csenha = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ccodigo = new javax.swing.JTextField();
        cespec = new javax.swing.JTextField();
        btnTodos = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        cDataNasc = new javax.swing.JFormattedTextField();
        ctelefone = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListProf = new javax.swing.JList<String>();

        setClosable(true);

        Prof.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        cnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnomeKeyTyped(evt);
            }
        });

        jLabel4.setText("E-mail:");

        jLabel3.setText("Senha:");

        jLabel1.setText("Código:");

        jLabel9.setText("Data Nasc.:");

        csexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Masculino", "Feminino" }));

        jLabel5.setText("Telefone:");

        jLabel6.setText("Endereço:");

        jLabel7.setText("Especialização:");

        jLabel8.setText("Sexo:");

        jLabel2.setText("Nome:");

        ccodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ccodigoFocusLost(evt);
            }
        });
        ccodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ccodigoKeyTyped(evt);
            }
        });

        cespec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cespecKeyTyped(evt);
            }
        });

        btnTodos.setText("Recaregar Lista");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(listener);
        btnExcluir.setActionCommand("excluir");
        caregabanco();
        limpar();

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(listener);
        btnSalvar.setActionCommand("salvar");
        caregabanco();
        limpar();

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(listener);
        btnAtualizar.setActionCommand("atualizar");
        caregabanco();
        limpar();

        try {
            cDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cDataNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cDataNascKeyTyped(evt);
            }
        });

        try {
            ctelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ctelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctelefoneKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout ProfLayout = new javax.swing.GroupLayout(Prof);
        Prof.setLayout(ProfLayout);
        ProfLayout.setHorizontalGroup(
            ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ccodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csexo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cemail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cespec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(ProfLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar)
                .addGap(10, 10, 10)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ProfLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cDataNasc, ccodigo, cemail, cendereco, cespec, cnome, csenha, csexo, ctelefone});

        ProfLayout.setVerticalGroup(
            ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(ccodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(cnome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(csenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(csexo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(cemail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ctelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(cendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(cespec, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodos)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar)
                    .addComponent(btnSalvar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        ProfLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cDataNasc, ccodigo, cemail, cendereco, cespec, cnome, csenha, csexo, ctelefone});

        ListProf.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ListProf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(Prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnomeKeyTyped
        if (numbers.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_cnomeKeyTyped

    private void ccodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ccodigoFocusLost

        String codTxt = ccodigo.getText().trim();
        if (codTxt.length() > 0) {
            Integer codigo = null;
            try {
                codigo = Integer.parseInt(codTxt);
            } catch (NumberFormatException e) {
                //o código informado é inválido
                return;
            }
            Professor P = dao.getProfessorbycode(codigo);
            if (P == null) {
                JOptionPane.showMessageDialog(this, "Aluno não encontrado!");
                limpar();
            } else {
                setProfessor(P);
            }
        }
    }//GEN-LAST:event_ccodigoFocusLost

    private void ccodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccodigoKeyTyped
        if (!numbers.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_ccodigoKeyTyped

    private void cespecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cespecKeyTyped
        if (numbers.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_cespecKeyTyped

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        caregabanco();
        limpar();
    }//GEN-LAST:event_btnTodosActionPerformed

    private void cDataNascKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cDataNascKeyTyped
        if (!numbers.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_cDataNascKeyTyped

    private void ctelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctelefoneKeyTyped
        if (!numbers.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_ctelefoneKeyTyped

    private void setProfessor(Professor p) {
        ccodigo.setText(String.valueOf(p.getCodProf()));
        cnome.setText(p.getNomeProf());
        csenha.setText(p.getSenhaProf());
        csexo.setSelectedItem(p.getSexo());
        cDataNasc.setText(p.getDataNasc());
        cemail.setText(p.getEmail());
        ctelefone.setText(p.getTelefone());
        cendereco.setText(p.getEndereco());
        cespec.setText(p.getEspecializacao());
    }
    
    private void limpar() {
        cnome.setText("");
        csenha.setText("");
        cDataNasc.setText("");
        cemail.setText("");
        ctelefone.setText("");
        cendereco.setText("");
        cespec.setText("");
    }
    
    private void caregabanco() {
        List<Professor> profList = dao.getAll();
        final Professor[] strings = new Professor[profList.size()];
        int i = 0;

        for (Professor p : profList) {
            strings[i++] = p;
        }
        ListProf.removeAll();
        ListProf.setModel(new javax.swing.AbstractListModel() {

            public int getSize() {
                return strings.length;
            }

            public Object getElementAt(int i) {
                return strings[i].getCodProf() + " - " + strings[i].getNomeProf();
            }
        });
    }

    public Professor getProfessor() throws Excecoes {

        if (valida.validaVazio(ccodigo)) {
            prof.setCodProf(Integer.parseInt(ccodigo.getText()));
        } else {
            throw new Excecoes("Campo Codigo é obrigatório!");
        }
        if (valida.validaVazio(cnome)) {
            prof.setNomeProf(cnome.getText());
        } else {
            throw new Excecoes("Campo Nome é obrigatório!");
        }
        if (valida.validaVazio(csenha)) {
            prof.setSenhaProf(Arrays.toString(csenha.getPassword()));
        } else {
            throw new Excecoes("Campo Senha é obrigatório!");
        }
        if (csexo.getSelectedIndex() != 0) {
            prof.setSexo(csexo.getSelectedItem().toString());
        } else {
            throw new Excecoes("Campo Sexo não definido!");
        }
        if (valida.validaData(cDataNasc)) {
            prof.setDataNasc(cDataNasc.getText());
        } else {
            throw new Excecoes("Campo Data é obrigatório!");
        }
        if (valida.validaVazio(cemail)) {
            prof.setEmail(cemail.getText());
        } else {
            throw new Excecoes("Campo Email é obrigatório!");
        }
        if (valida.validaVazio(ctelefone)) {
            prof.setTelefone(ctelefone.getText());
        } else {
            throw new Excecoes("Campo Telefone é obrigatório!");
        }
        if (valida.validaVazio(cendereco)) {
            prof.setEndereco(cendereco.getText());
        } else {
            throw new Excecoes("Campo Endereço é obrigatório!");
        }
        if (valida.validaVazio(cespec)) {
            prof.setEspecializacao(cespec.getText());
        } else {
            throw new Excecoes("Campo Responsável é obrigatório!");
        }

        return prof;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListProf;
    private javax.swing.JPanel Prof;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JFormattedTextField cDataNasc;
    private javax.swing.JTextField ccodigo;
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField cendereco;
    private javax.swing.JTextField cespec;
    private javax.swing.JTextField cnome;
    private javax.swing.JPasswordField csenha;
    private javax.swing.JComboBox<String> csexo;
    private javax.swing.JFormattedTextField ctelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
